ispravlena
elleune/java-kanban pull request #28
Opened 2024-07-18 18:52 UTC by elleune

2024-07-18 19:14 UTC, elleune commented
Роман, привет! Не могу найти тебя в "Пачке" с пулом у меня беда не сразу поняла как с ним работать. Постоянно  у меня на что то ругается. Сделала изменения в классе InMemoryHistoryManager (можно сказать заново переписала), добавила тесты в HistoryManagerTest, более изменений глобальных не было, в основном ошибки в стиле оформления кода. И во время отправки работы не сразу удалось всех "подружить".

2024-07-19 19:33 UTC, Fleaman777 requested changes
не увидел тест кейса, который проверяет, что в истории теперь можно сохранить неограниченное количество задач, 

Посмотри какие еще тест кейсы для менеджера задач  нужно добавить согласно ТЗ

2024-07-19 19:33 UTC, Fleaman777 commented on test/HistoryManagerTest.java
>          HistoryManager historyManager = Managers.getDefaultHistory();
лучше создать поле HistoryManager historyManager  в тестовом классе,и проинициализировать его в методе с аннотацией @BeforeEach, так нам не придется дублировать создание менеджера в каждом тесте

создание тестовой задачи тоже можно создавать в общем методе, и потом применять его так, где нужно

2024-07-19 19:33 UTC, Fleaman777 commented on test/HistoryManagerTest.java
>      void add() {
что бы при поиске метода по всему проекту на отвлекаться на тесты, лучше тесты называть иначе, чем методы основных классов,
хорошо бы в названии упоминать при каких условиях выполняется тест и какой результат ожидается

2024-07-19 19:37 UTC, Fleaman777 commented
да, с пулл реквестами хорошо потренировалась, надеюсь теперь принцип понятен и в следующем спринте все получится как необходимо))

этот зачту в таком состоянии, в каком есть, так как необходимый код все же написан, но он уже в мастере, что конечно не правильно, относительно того, как должны сдаваться задания

2024-07-22 20:19 UTC, elleune commented
Исправления внесены

2024-07-22 20:20 UTC, closed without merging